language: swift
osx_image: xcode15.4
before_install:
  - brew install xcodegen
script:
  - xcodegen
  - xcodebuild -scheme App -project App.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' build
after_success:
  - bash <(curl -s https://codecov.io/bash)
