name: Example
targets:
  Example:
    type: application
    platform: iOS
    deploymentTarget: 12.0
    sources:
      - path: Sources
      - path: www
        type: folder
    settings:
      INFOPLIST_FILE: Sources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.bommko.UniversalWebView
      ENABLE_BITCODE: NO
      CURRENT_PROJECT_VERSION: 1
